# Generated by Django 3.2 on 2021-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('hotel', models.CharField(max_length=70)),
                ('review', models.CharField(max_length=10000)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
